name: Build APK

on:
  push:
    branches: [ "main_ci" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10.12"

    # ✅ ФИКС: ставим Java 17 нормально
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install system deps
      run: |
        sudo apt update
        sudo apt install -y \
          git zip unzip \
          autoconf libtool pkg-config \
          zlib1g-dev libncurses5-dev \
          libncursesw5-dev cmake \
          libffi-dev libssl-dev

    - name: Install Python deps
      run: |
        pip install --upgrade pip
        pip install buildozer cython


    - name: Set SDK env
      run: |
        echo "ANDROID_SDK_ROOT=$PWD/android-sdk" >> $GITHUB_ENV

    # ✅ ФИКС: правильная установка SDK
    - name: Setup Android SDK
      run: |
        mkdir -p android-sdk/cmdline-tools

        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip commandlinetools-linux-*.zip -d android-sdk/cmdline-tools

        mv android-sdk/cmdline-tools/cmdline-tools android-sdk/cmdline-tools/latest

        export ANDROID_SDK_ROOT=$PWD/android-sdk
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH

        yes | sdkmanager --licenses

        sdkmanager "platform-tools" "platforms;android-31" "build-tools;37.0.0"

    - name: Download Android NDK
      run: |
        wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip -O ndk.zip
        unzip -q ndk.zip
        mv android-ndk-r25b android-ndk

    - name: Set NDK environment
      run: |
        echo "ANDROID_NDK_HOME=$PWD/android-ndk" >> $GITHUB_ENV
        echo "ANDROIDNDK=$PWD/android-ndk" >> $GITHUB_ENV
        echo "NDK_HOME=$PWD/android-ndk" >> $GITHUB_ENV

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: dislexify-apk
        path: bin/*.apk