name: Build APK

on:
  push:
    branches: [ "main_ci" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10.12"

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: "17"

    - name: Install system deps
      run: |
        sudo apt update
        sudo apt install -y \
          git zip unzip wget \
          autoconf libtool pkg-config \
          cmake build-essential \
          libffi-dev libssl-dev \
          zlib1g-dev libncurses5-dev libncursesw5-dev

    - name: Install Python deps
      run: |
        pip install --upgrade pip
        pip install buildozer cython

    # 🔥 FIX git network issues
    - name: Git config fix
      run: |
        git config --global http.postBuffer 524288000
        git config --global http.version HTTP/1.1

    # 🔥 Android SDK
    - name: Setup Android SDK
      run: |
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools

        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip commandlinetools-linux-*.zip -d $ANDROID_SDK_ROOT/cmdline-tools

        mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest

        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH

        yes | sdkmanager --licenses || true

        sdkmanager --update

        sdkmanager \
          "platform-tools" \
          "platforms;android-31" \
          "build-tools;30.0.3"

    # ❌ NO NDK (Buildozer сам скачает правильный)
    # УДАЛЕНО полностью

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: dislexify-apk
        path: bin/*.apk